<!-- Generated by Vue on Rails https://github.com/vueonrails/vueonrails -->
<!-- The corresponding pack is app/javascript/packs/form.js -->
<!-- Generate another component part like this by running command `rails generate vue something` -->

<template>
  <form-for model="student">
    <div class="field">
      <label-tag for="name">Name</label-tag>
      <text-field for="name"></text-field>
    </div>

    <fields-for model="subjects" >
        <label-tag for="name">Subject</label-tag>
        <text-field for="name"></text-field>
    </fields-for>

    <div class="actions">
      <submit-tag></submit-tag>
    </div>
  </form-for>
</template>

<script>

// import store from '@/store'
export default {
  data: function() {
    return {
      message: "Hello form!"
    };
  },
  watch: {
    onCreated: function(response) {
      this.items = response.data;
    }
  },
  methods: {
    //Add the button to your .vue template: <button @click="onClick">click this</button>
    onClick: function() {
      console.log("clicked");
    }
  },
  computed: {}
  // props: {},
  // components: {},
  // mixins: [],
  // directives: {},
  // filters: {},
  // asyncComputed: {},
};
</script>

<style>
p {
  font-size: 2em;
  text-align: center;
}
</style>
