// Generated by Vue on Rails https://github.com/vueonrails/vueonrails
// Display this Vue component on Rails View by adding `require('./form')` to app/javascript/application.js
// Generate a component part by running command `rails generate vue something`

import Vue from 'vue'
import App from '@/form.vue'
import form from 'vue-form-for'
import {isView} from 'vueonrails'

Vue.use(form)

document.addEventListener('DOMContentLoaded', () => {
  if(isView('students#new')){
    document.body.appendChild(document.createElement('form'))
    const form = new Vue({
      render: h => h(App)
    }).$mount('form')
    console.log({form})
  }
})

